### ISSUE TITLE
provisioner connection didn't connect to cvm but connect to localhost

### ISSUE THREAD

**Issue by jhsea3do** [tencentyun/terraform-provider-tencentcloud#71]
version = 1.2.1
i try to use provisioner 'file' upload some files to the new cloud vm (CVM) ,
but none file uploaded, all files go up to the localhost (my terraform controller).
btw, the `remote-exec` also runs in the localhost.

my codes:
```ruby

resource "tencentcloud_instance" "node1" {
....
  provisioner "remote-exec" {
    inline = [
      "mkdir -p /tmp/111222",
      "mkdir -p ${var.app_home}",
    ]

    connection {
      type        = "ssh"
      user        = "${var.ssh_user}"
      private_key = "${file(var.private_key_path)}"
    }
  }


  provisioner "file" {
    source      = "plays/"
    destination = "${var.app_home}/plays"

    connection {
      type        = "ssh"
      user        = "${var.ssh_user}"
      private_key = "${file(var.private_key_path)}"
    }
  }

  provisioner "file" {
    source      = "envs/"
    destination = "${var.app_home}/envs"

    connection {
      type        = "ssh"
      user        = "${var.ssh_user}"
      private_key = "${file(var.private_key_path)}"
    }
  }
...
}
```

here is provisions log:
```yaml
module.tencentcloud-play1.tencentcloud_instance.node1: Provisioning with 'remote-exec'...
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec): Connecting to remote host via SSH...
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   Host:
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   User: root
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   Password: false
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   Private key: true
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   SSH Agent: false
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   Checking Host Key: false
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec): Connected!
module.tencentcloud-play1.tencentcloud_instance.node1: Provisioning with 'file'...
module.tencentcloud-play1.tencentcloud_instance.node1: Provisioning with 'file'...
module.tencentcloud-play1.tencentcloud_instance.node1: Provisioning with 'file'...
module.tencentcloud-play1.tencentcloud_instance.node1: Provisioning with 'file'...
module.tencentcloud-play1.tencentcloud_instance.node1: Provisioning with 'file'...
module.tencentcloud-play1.tencentcloud_instance.node1: Provisioning with 'file'...
module.tencentcloud-play1.tencentcloud_instance.node1: Provisioning with 'file'...
module.tencentcloud-play1.tencentcloud_instance.node1: Provisioning with 'file'...
module.tencentcloud-play1.tencentcloud_instance.node1: Provisioning with 'remote-exec'...
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec): Connecting to remote host via SSH...
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   Host:
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   User: root
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   Password: false
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   Private key: true
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   SSH Agent: false
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   Checking Host Key: false
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec): Connected!

```

**Comment by zqfan** [comment]
@jhsea3do  can you check which security group you have attached to this virtual machine, and does it open 22 port?

**Comment by jhsea3do** [comment]
@zqfan 

why the log shows `Connected` ?

I tried it again, please notice that the `Host` value is empty.

I didn't create any security group, but i can connect the vm via public ip  after i created it (means Port 22 is open).

```yaml
module.tencentcloud-play1.tencentcloud_instance.node1: Provisioning with 'remote-exec'...
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec): Connecting to remote host via SSH...
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   Host:
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   User: root
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   Password: false
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   Private key: true
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   SSH Agent: false
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   Checking Host Key: false
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec): Connected!
```

**Comment by jhsea3do** [comment]
I've attached one security group, but the provision still upload files and execute script in my terraform control node.

```yaml
module.tencentcloud-play1.tencentcloud_instance.node1: Creating...
  allocate_public_ip:         "" => "false"
  availability_zone:          "" => "ap-guangzhou-3"
  data_disks.#:               "" => "<computed>"
  disable_monitor_service:    "" => "true"
  disable_security_service:   "" => "true"
  image_id:                   "" => "img-31tjrtph"
  instance_charge_type:       "" => "POSTPAID_BY_HOUR"
  instance_name:              "" => "node1"
  instance_status:            "" => "<computed>"
  instance_type:              "" => "S1.SMALL2"
  internet_max_bandwidth_out: "" => "2"
  key_name:                   "" => "skey-dknj6zej"
  private_ip:                 "" => "<computed>"
  public_ip:                  "" => "<computed>"
  security_groups.#:          "" => "1"
  security_groups.4278077757: "" => "sg-mxgr9e83"
  subnet_id:                  "" => "subnet-c9jgo6ky"
  system_disk_size:           "" => "<computed>"
  system_disk_type:           "" => "CLOUD_BASIC"
  user_data:                  "" => "IyEvYmluL3NoCm1rZGlyIC1wIC90bXAveHhvbwplY2hvIDEyMzQ1ID4gL3RtcC9vb3h4LmxvZwo="
  vpc_id:                     "" => "vpc-r6a2albf"
module.tencentcloud-play1.tencentcloud_instance.node1: Still creating... (10s elapsed)
module.tencentcloud-play1.tencentcloud_instance.node1: Still creating... (20s elapsed)
module.tencentcloud-play1.tencentcloud_instance.node1: Still creating... (30s elapsed)
module.tencentcloud-play1.tencentcloud_instance.node1: Provisioning with 'remote-exec'...
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec): Connecting to remote host via SSH...
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   Host:
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   User: root
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   Password: false
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   Private key: true
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   SSH Agent: false
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec):   Checking Host Key: false
module.tencentcloud-play1.tencentcloud_instance.node1 (remote-exec): Connected!
module.tencentcloud-play1.tencentcloud_instance.node1: Provisioning with 'file'...
module.tencentcloud-play1.tencentcloud_instance.node1: Creation complete after 39s (ID: ins-cuk1htlw)

Apply complete! Resources: 4 added, 0 changed, 0 destroyed.
```

![image](https://user-images.githubusercontent.com/91740/45662736-a292f180-bb35-11e8-8f35-1c5e56153d1b.png)

![image](https://user-images.githubusercontent.com/91740/45662673-5e9fec80-bb35-11e8-8ecc-11c662adc4f1.png)
